# Generated by Django 5.2.17 on 2026-09-29 05:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(default="default", max_length=30, unique=True),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("tavily", "Tavily"), ("brave", "Brave Search")],
                        default="tavily",
                        max_length=20,
                    ),
                ),
                ("api_key", models.TextField(blank=True)),
                ("max_sources", models.PositiveSmallIntegerField(default=6)),
                ("daily_limit", models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnterpriseProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(default=dict)),
                ("evidence", models.JSONField(default=dict)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnterpriseProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("data", models.JSONField(default=dict)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="enterprises.enterpriseprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResearchRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(default="company", max_length=20)),
                ("inputs", models.JSONField(default=dict)),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(db_index=True, default="queued", max_length=20),
                ),
                ("stage", models.CharField(default="等待处理", max_length=100)),
                ("result", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("lease_token", models.UUIDField(null=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enterprises.enterpriseprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
