# Generated by Django 5.2.17 on 2026-09-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterpriseprofile",
            name="next_research_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enterpriseprofile",
            name="refresh_days",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
