# Generated by Django 5.2.17 on 2026-09-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0002_enterpriseprofile_next_research_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterpriseprofile",
            name="research_method",
            field=models.CharField(default="search", max_length=20),
        ),
        migrations.AddField(
            model_name="researchrun",
            name="uploaded_material",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
