# Generated by Django 5.2.17 on 2026-09-30 08:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0004_searxng"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchrun",
            name="agent_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="researchrun",
            name="checkpoint",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="researchrun",
            name="retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="researchrun",
            name="usage",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="researchsettings",
            name="agent_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="researchsettings",
            name="agent_max_calls",
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="researchsettings",
            name="agent_max_reads",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="researchsettings",
            name="agent_max_seconds",
            field=models.PositiveIntegerField(default=480),
        ),
        migrations.AddField(
            model_name="researchsettings",
            name="agent_organizations",
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name="ResearchArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(default=dict)),
                ("kind", models.CharField(default="company_draft", max_length=30)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact",
                        to="enterprises.researchrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResearchStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("label", models.CharField(max_length=120)),
                ("tool", models.CharField(max_length=40)),
                ("status", models.CharField(default="running", max_length=20)),
                ("detail", models.CharField(blank=True, max_length=400)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="enterprises.researchrun",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "sequence"), name="unique_research_step"
                    )
                ],
            },
        ),
    ]
