# Generated by Django 5.2.17 on 2026-10-02 16:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0006_researchsettings_agent_all_organizations'),
        ('policies', '0018_aireviewcontrol_recovery_attempt_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='default', max_length=30, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('all_organizations', models.BooleanField(default=True)),
                ('organizations', models.JSONField(default=list)),
                ('batch_size', models.PositiveSmallIntegerField(default=30)),
                ('daily_batches', models.PositiveIntegerField(default=200)),
                ('daily_model_calls', models.PositiveIntegerField(default=20)),
                ('model_calls_per_run', models.PositiveSmallIntegerField(default=2)),
                ('aggregation_minutes', models.PositiveSmallIntegerField(default=10)),
                ('retention_days', models.PositiveSmallIntegerField(default=90)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyWatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('view', models.CharField(default='opportunities', max_length=20)),
                ('interval_hours', models.PositiveSmallIntegerField(default=24)),
                ('ai_explanations', models.BooleanField(default=False)),
                ('consent_version', models.PositiveIntegerField(default=1)),
                ('consented_at', models.DateTimeField(null=True)),
                ('next_run_at', models.DateTimeField(null=True)),
                ('last_run_at', models.DateTimeField(null=True)),
                ('last_full_scan_at', models.DateTimeField(null=True)),
                ('event_watermark', models.DateTimeField(null=True)),
                ('input_signature', models.CharField(blank=True, max_length=64)),
                ('has_baseline', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=400)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterpriseprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterpriseproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('content_fingerprint', models.CharField(max_length=64)),
                ('profile_revision', models.PositiveIntegerField()),
                ('project_revision', models.PositiveIntegerField(null=True)),
                ('policy_version', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('result', models.JSONField(default=dict)),
                ('feedback', models.CharField(blank=True, max_length=20)),
                ('feedback_note', models.CharField(blank=True, max_length=500)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policy')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='enterprises.policywatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(db_index=True, default='queued', max_length=20)),
                ('signature', models.CharField(max_length=64)),
                ('cutoff', models.DateTimeField()),
                ('full_scan', models.BooleanField(default=False)),
                ('notify_changes', models.BooleanField(default=False)),
                ('cursor', models.UUIDField(null=True)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('retry_at', models.DateTimeField(null=True)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('scanned', models.PositiveIntegerField(default=0)),
                ('matched', models.PositiveIntegerField(default=0)),
                ('model_calls', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=400)),
                ('finished_at', models.DateTimeField(null=True)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='enterprises.policywatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='policywatch',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('user', 'profile'), name='unique_company_policy_watch'),
        ),
        migrations.AddConstraint(
            model_name='policywatch',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('user', 'project'), name='unique_project_policy_watch'),
        ),
        migrations.AddConstraint(
            model_name='policyrecommendation',
            constraint=models.UniqueConstraint(fields=('watch', 'policy', 'fingerprint'), name='unique_policy_recommendation'),
        ),
        migrations.AddConstraint(
            model_name='watchrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('watch',), name='one_active_watch_run'),
        ),
    ]
