# Generated by Django 5.2.17 on 2026-10-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0007_recommendationsettings_policywatch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchrun",
            name="runtime_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="researchstep",
            name="execution_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
