# Generated by Django 5.2.17 on 2026-10-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0009_researchrun_parent_researchrun_unique_workflow_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsettings',
            name='workflow_max_calls',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='researchsettings',
            name='workflow_max_policies',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='researchsettings',
            name='workflow_max_seconds',
            field=models.PositiveIntegerField(default=480),
        ),
    ]
