# Generated by Django 5.2.17 on 2026-10-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0010_researchsettings_workflow_max_calls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsettings',
            name='workflow_cache_hours',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='researchsettings',
            name='workflow_concurrency',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='researchsettings',
            name='workflow_daily_calls',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='researchsettings',
            name='workflow_gap_fill',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='researchsettings',
            name='workflow_retry_limit',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
