# Generated by Django 5.2.17 on 2026-09-27 12:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("knowledge", "0003_relationreviewcandidate"),
        ("policies", "0017_seed_publication_consumers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="completed", max_length=20)),
                (
                    "protocol_version",
                    models.CharField(default="quality-v1", max_length=40),
                ),
                ("config_version", models.CharField(blank=True, max_length=100)),
                ("metrics", models.JSONField(default=dict)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationSample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("opportunity", "政策机会识别"),
                            ("relation", "Wiki政策关系"),
                            ("knowledge", "Wiki知识页证据"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("relation_kind", models.CharField(blank=True, max_length=24)),
                ("snapshot", models.JSONField(default=dict)),
                ("origin", models.CharField(default="manual", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待人工标注"),
                            ("labeled", "已人工标注"),
                            ("retired", "已停用"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gold", models.JSONField(default=dict)),
                ("label_version", models.PositiveIntegerField(default=0)),
                ("labeled_at", models.DateTimeField(null=True)),
                (
                    "labeled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="knowledge.knowledgepage",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="policies.policy",
                    ),
                ),
                (
                    "related_policy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label_version", models.PositiveIntegerField()),
                ("status", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True)),
                ("gold", models.JSONField(default=dict)),
                ("prediction", models.JSONField(default=dict)),
                ("correct", models.BooleanField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="quality.evaluationrun",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quality.evaluationsample",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "sample"), name="unique_quality_run_sample"
                    )
                ],
            },
        ),
    ]
