# Generated by Django 5.2.17 on 2026-10-02 17:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0007_recommendationsettings_policywatch_and_more'),
        ('policies', '0018_aireviewcontrol_recovery_attempt_limit_and_more'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hour', models.DateTimeField(unique=True)),
                ('metrics', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-hour'],
            },
        ),
        migrations.CreateModel(
            name='MatchingStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view', models.CharField(max_length=20)),
                ('snapshot', models.JSONField(default=dict)),
                ('selection', models.JSONField(default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterpriseprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterpriseproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatchingCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('predicted', models.BooleanField()),
                ('prediction', models.JSONField(default=dict)),
                ('verdict', models.CharField(default='pending', max_length=20)),
                ('evidence_supported', models.BooleanField(null=True)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('quote', models.TextField(blank=True)),
                ('label_version', models.PositiveIntegerField(default=0)),
                ('labeled_at', models.DateTimeField(null=True)),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.policy')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='quality.matchingstudy')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('study', 'policy'), name='unique_matching_study_policy')],
            },
        ),
    ]
