# Generated by Django 5.2.17 on 2026-09-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "全部类型"),
                    ("policy", "政策与制度文件"),
                    ("opportunity", "政策机会文件"),
                    ("result", "政策执行结果"),
                    ("interpretation", "官方解读"),
                    ("draft", "征求意见稿"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
