# Generated by Django 5.2.17 on 2026-09-30 07:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0004_searxng"),
        ("policies", "0017_seed_publication_consumers"),
        ("subscriptions", "0003_structured_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "update_mode",
                    models.CharField(
                        choices=[("daily", "每日汇总"), ("instant", "即时通知")],
                        default="daily",
                        max_length=12,
                    ),
                ),
                ("digest_hour", models.PositiveSmallIntegerField(default=9)),
                ("deadline_enabled", models.BooleanField(default=False)),
                (
                    "deadline_days",
                    models.JSONField(
                        default=subscriptions.models.default_deadline_days
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PendingDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reasons", models.JSONField(default=list)),
                ("handled_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProfileFollow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=False)),
                ("last_profile_revision", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("reason", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="delivery_key",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="notification",
            name="digest_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="kind",
            field=models.CharField(default="update", max_length=20),
        ),
        migrations.AddField(
            model_name="subscription",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="interest_regions",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="subscription",
            name="managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="subscription",
            name="source_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="enterprises.enterpriseprofile",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="system_paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="policies.publicationevent",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("user", "digest_date"), name="unique_user_daily_digest"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("delivery_key", ""), _negated=True),
                fields=("user", "delivery_key"),
                name="unique_notification_delivery_key",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pendingdelivery",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="policies.publicationevent",
            ),
        ),
        migrations.AddField(
            model_name="pendingdelivery",
            name="notification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="subscriptions.notification",
            ),
        ),
        migrations.AddField(
            model_name="pendingdelivery",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="profilefollow",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enterprises.enterpriseprofile",
            ),
        ),
        migrations.AddField(
            model_name="profilefollow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="subscriptionchange",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionchange",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changes",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingdelivery",
            constraint=models.UniqueConstraint(
                fields=("user", "event"), name="unique_pending_delivery"
            ),
        ),
        migrations.AddConstraint(
            model_name="profilefollow",
            constraint=models.UniqueConstraint(
                fields=("user", "profile"), name="unique_profile_follow"
            ),
        ),
    ]
