# Generated by Django 5.2.17 on 2026-10-02 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0007_recommendationsettings_policywatch_and_more'),
        ('policies', '0018_aireviewcontrol_recovery_attempt_limit_and_more'),
        ('subscriptions', '0004_notificationpreference_pendingdelivery_profilefollow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprises.policyrecommendation'),
        ),
        migrations.AddField(
            model_name='pendingdelivery',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprises.policyrecommendation'),
        ),
        migrations.AlterField(
            model_name='pendingdelivery',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='policies.publicationevent'),
        ),
        migrations.AddConstraint(
            model_name='pendingdelivery',
            constraint=models.UniqueConstraint(fields=('user', 'recommendation'), name='unique_pending_recommendation'),
        ),
    ]
