# Generated by Django 5.2.17 on 2026-10-02 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0007_recommendationsettings_policywatch_and_more'),
        ('subscriptions', '0005_notification_recommendation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profilefollow',
            name='unique_profile_follow',
        ),
        migrations.AddField(
            model_name='profilefollow',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterpriseproject'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='source_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterpriseproject'),
        ),
        migrations.AddConstraint(
            model_name='profilefollow',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('user', 'profile'), name='unique_company_follow'),
        ),
        migrations.AddConstraint(
            model_name='profilefollow',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('user', 'project'), name='unique_project_follow'),
        ),
    ]
