# Generated by Django 5.2.17 on 2026-10-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("manage_system", "管理系统配置与运行监控")],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
