# Generated by Django 5.2.17 on 2026-09-15 04:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("document_number", models.CharField(blank=True, max_length=200)),
                ("issuer", models.CharField(max_length=200)),
                ("publication_date", models.DateField()),
                ("region", models.CharField(default="全国", max_length=100)),
                ("topics", models.JSONField(default=list)),
                ("body", models.TextField()),
                ("source_url", models.URLField(max_length=2000)),
                ("source_key", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "待审核"),
                            ("published", "已发布"),
                            ("withdrawn", "已撤下"),
                        ],
                        default="candidate",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_demo", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-publication_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-publication_date"],
                        name="policies_po_status_f8bff5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("policy_version", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("location", models.JSONField(default=dict)),
                ("quote_hash", models.CharField(max_length=64)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=2000)),
                ("sha256", models.CharField(max_length=64)),
                ("object_key", models.CharField(max_length=500)),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("parse_status", models.CharField(default="pending", max_length=30)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("policy", "sha256"), name="unique_snapshot")
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("policy_version", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(default="policy.published.v1", max_length=80),
                ),
                ("payload", models.JSONField()),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "policy_version", "kind"),
                        name="unique_publication_event",
                    )
                ],
            },
        ),
    ]
