# Generated by Django 5.2.17 on 2026-09-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("unclassified", "待分类"),
                    ("policy", "政策与制度文件"),
                    ("opportunity", "政策机会文件"),
                    ("result", "政策执行结果"),
                    ("interpretation", "官方解读"),
                    ("draft", "征求意见稿"),
                ],
                db_index=True,
                default="unclassified",
                max_length=30,
            ),
        ),
    ]
