# Generated by Django 5.2.17 on 2026-09-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0002_policy_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="policy",
            name="geographic_level",
            field=models.CharField(
                choices=[
                    ("unverified", "待核验"),
                    ("national", "国家级"),
                    ("provincial", "省级"),
                    ("city", "地级市级"),
                ],
                db_index=True,
                default="unverified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="policy",
            name="source_grade",
            field=models.CharField(
                choices=[
                    ("unverified", "待核验"),
                    ("L1", "官方原始"),
                    ("L2", "官方转载"),
                    ("L3", "政府官方业务平台"),
                    ("L4", "非官方线索"),
                ],
                db_index=True,
                default="unverified",
                max_length=20,
            ),
        ),
    ]
