# Generated by Django 5.2.17 on 2026-09-16 07:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "policies",
            "0003_policy_city_policy_geographic_level_policy_province_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="extraction_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="policy",
            name="structured_keywords",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="policy",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="validity_evidence",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="validity_status",
            field=models.CharField(
                choices=[
                    ("consultation", "征求意见"),
                    ("not_effective", "尚未生效"),
                    ("effective", "现行有效"),
                    ("expired", "已失效"),
                    ("repealed", "已废止"),
                    ("replaced", "已被替代/已修订"),
                    ("unverified", "待核实"),
                ],
                db_index=True,
                default="unverified",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "待核验"),
                            ("verified", "已核验"),
                            ("rejected", "核验不通过"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("evidence_version", models.PositiveIntegerField()),
                ("evidence_quote", models.TextField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fiscal", "财政资金支持"),
                            ("tax", "税费优惠"),
                            ("finance", "融资支持"),
                            ("pilot", "项目与试点"),
                            ("honor", "荣誉与认定"),
                            ("qualification", "资质与目录"),
                            ("market", "市场与推广支持"),
                            ("other", "其他政策支持"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("open", "申报中"),
                            ("closed", "已截止"),
                            ("ongoing", "长期有效/常态化受理"),
                            ("suspended", "暂停/中止"),
                            ("publicity", "结果公示中"),
                            ("completed", "已完成"),
                            ("unverified", "待核实"),
                        ],
                        default="unverified",
                        max_length=24,
                    ),
                ),
                (
                    "evidence_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.policy",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="policies.policy",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "待核验"),
                            ("verified", "已核验"),
                            ("rejected", "核验不通过"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("evidence_version", models.PositiveIntegerField()),
                ("evidence_quote", models.TextField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("open", "申报中"),
                            ("closed", "已截止"),
                            ("ongoing", "长期有效/常态化受理"),
                            ("suspended", "暂停/中止"),
                            ("publicity", "结果公示中"),
                            ("completed", "已完成"),
                            ("unverified", "待核实"),
                        ],
                        default="unverified",
                        max_length=24,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deadline_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "evidence_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.policy",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="policies.opportunity",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["deadline_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("opportunity", "name"),
                        name="unique_opportunity_batch_name",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("starts_at__isnull", True),
                            ("deadline_at__isnull", True),
                            ("deadline_at__gte", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="batch_deadline_after_start",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "待核验"),
                            ("verified", "已核验"),
                            ("rejected", "核验不通过"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("evidence_version", models.PositiveIntegerField()),
                ("evidence_quote", models.TextField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("superior", "上位"),
                            ("implements", "实施"),
                            ("supports", "配套"),
                            ("application", "申报通知"),
                            ("supplements", "补充"),
                            ("extends", "延期"),
                            ("interprets", "解读"),
                            ("finalizes", "征求→正式"),
                            ("revises", "修订"),
                            ("replaces", "替代"),
                            ("repeals", "废止"),
                            ("publicizes", "公示"),
                            ("lists", "正式名单"),
                            ("allocates", "资金下达"),
                            ("approves", "项目批复"),
                            ("accepts", "验收结果"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "evidence_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.policy",
                    ),
                ),
                (
                    "from_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_relations",
                        to="policies.policy",
                    ),
                ),
                (
                    "to_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_relations",
                        to="policies.policy",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_policy", "to_policy", "kind"),
                        name="unique_directed_policy_relation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("from_policy", models.F("to_policy")), _negated=True),
                        name="no_self_policy_relation",
                    ),
                ],
            },
        ),
    ]
