# Generated by Django 5.2.17 on 2026-09-16 14:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "policies",
            "0004_policy_extraction_version_policy_structured_keywords_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="summary_evidence",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="policy",
            name="summary_method",
            field=models.CharField(default="extractive", max_length=20),
        ),
        migrations.AddField(
            model_name="policyrelation",
            name="discovery",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="PolicyEnrichment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("policy_version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(db_index=True, default="queued", max_length=20),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("retry_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("model", models.CharField(blank=True, max_length=200)),
                (
                    "prompt_version",
                    models.CharField(default="policy-enrichment-v1", max_length=30),
                ),
                ("result", models.JSONField(default=dict)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichments",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "policy_version"),
                        name="unique_policy_enrichment",
                    )
                ],
            },
        ),
    ]
