# Generated by Django 5.2.17 on 2026-09-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0005_policy_summary_evidence_policy_summary_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="business_domains",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="policy",
            name="direction_tags",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="policy",
            name="industry",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="policy",
            name="scope_evidence",
            field=models.JSONField(default=dict),
        ),
    ]
