# Generated by Django 5.2.17 on 2026-09-22 06:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0013_opportunity_analysis_v11"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyFieldProvenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("policy_version", models.PositiveIntegerField()),
                ("field_name", models.CharField(db_index=True, max_length=80)),
                ("value_snapshot", models.JSONField(null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("source_metadata", "官方来源信息"),
                            ("deterministic_rule", "确定性规则"),
                            ("ai_review", "AI审核"),
                            ("wiki_llm", "Wiki LLM"),
                            ("human_correction", "人工修正"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("evidence_quote", models.TextField(blank=True)),
                ("evidence_location", models.JSONField(blank=True, default=dict)),
                ("model", models.CharField(blank=True, max_length=200)),
                ("prompt_version", models.CharField(blank=True, max_length=40)),
                ("config_version", models.CharField(blank=True, max_length=80)),
                ("locked", models.BooleanField(db_index=True, default=False)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_provenance",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "ordering": ["field_name", "-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["policy", "field_name", "-created_at"],
                        name="policies_po_policy__3d1d4f_idx",
                    ),
                    models.Index(
                        fields=["policy", "locked"],
                        name="policies_po_policy__7fe6bf_idx",
                    ),
                ],
            },
        ),
    ]
