# Generated by Django 5.2.17 on 2026-09-27 12:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_relationreviewcandidate"),
        ("policies", "0015_backfill_policy_field_provenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationConsumption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consumer",
                    models.CharField(
                        choices=[
                            ("search", "搜索同步"),
                            ("subscription", "订阅通知"),
                            ("wiki", "Wiki 知识构建"),
                            ("statistics", "统计审计"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待处理"),
                            ("running", "正在处理"),
                            ("waiting", "等待知识构建完成"),
                            ("retry", "等待自动重试"),
                            ("failed", "需要处理"),
                            ("succeeded", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("failures", models.PositiveIntegerField(default=0)),
                ("retry_at", models.DateTimeField(blank=True, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "last_success_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("succeeded_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(default=dict)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumptions",
                        to="policies.publicationevent",
                    ),
                ),
                (
                    "wiki_build",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="knowledge.knowledgebuild",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["consumer", "status", "retry_at"],
                        name="event_consumer_due",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "consumer"), name="unique_event_consumer"
                    )
                ],
            },
        ),
    ]
