# Generated by Django 5.2.17 on 2026-10-02 15:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0017_seed_publication_consumers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aireviewcontrol",
            name="recovery_attempt_limit",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="aireviewcontrol",
            name="recovery_cooldown_minutes",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="aireviewcontrol",
            name="recovery_daily_limit",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="aireviewcontrol",
            name="recovery_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="policyenrichment",
            name="recovery_token",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="ReviewRecovery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("policy_version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(db_index=True, default="queued", max_length=20),
                ),
                ("category", models.CharField(blank=True, max_length=30)),
                ("stage", models.CharField(default="等待异常处理", max_length=100)),
                ("message", models.TextField(blank=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("retry_at", models.DateTimeField(blank=True, null=True)),
                ("automatic", models.BooleanField(default=False)),
                ("result", models.JSONField(default=dict)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_recoveries",
                        to="policies.policy",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery",
                        to="policies.policyenrichment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
