# Generated by Django 5.2.17 on 2026-10-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0018_aireviewcontrol_recovery_attempt_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyenrichment',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
