# Generated by Django 5.2.17 on 2026-09-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_aimodelprofile_concurrency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodelprofile",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("review", "政策自动审核与摘要"),
                    ("search", "自然语言检索与归纳"),
                    ("wiki_synthesis", "Wiki 知识页综合"),
                    ("wiki_relations", "政策关系发现"),
                    ("enterprise", "企业画像与匹配解读"),
                ],
                max_length=40,
                unique=True,
            ),
        ),
    ]
