# Generated by Django 5.2.17 on 2026-10-02 18:24

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_aimodelprofile_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelprofile',
            name='currency',
            field=models.CharField(choices=[('CNY', '人民币'), ('USD', '美元')], default='CNY', max_length=3),
        ),
        migrations.AddField(
            model_name='aimodelprofile',
            name='input_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='aimodelprofile',
            name='output_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='AICall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('duration_ms', models.PositiveIntegerField()),
                ('input_tokens', models.PositiveBigIntegerField(null=True)),
                ('output_tokens', models.PositiveBigIntegerField(null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('input_price', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('output_price', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at', 'purpose'], name='ai_call_usage_period')],
            },
        ),
    ]
