# Generated by Django 5.2.17 on 2026-10-03 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_aimodelprofile_currency_aimodelprofile_input_price_and_more"),
        ("enterprises", "0008_researchrun_runtime_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aicall",
            name="step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="model_requests",
                to="enterprises.researchstep",
            ),
        ),
        migrations.AddField(
            model_name="aicall",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="model_requests",
                to="enterprises.researchrun",
            ),
        ),
    ]
