# Generated by Django 5.2.17 on 2026-10-03 09:50

import django.core.validators
from django.db import migrations, models


def inherit_models(apps, schema_editor):
    model = apps.get_model("core", "AIModelProfile")
    fields = ["enabled", "base_url", "api_key", "model", "concurrency", "input_price", "output_price", "currency", "thinking", "context_tokens", "max_output_tokens"]
    for purpose, parent in [("search_summary", "search"), ("enterprise_match", "enterprise")]:
        source = model.objects.using(schema_editor.connection.alias).filter(purpose=parent).first()
        if source:
            model.objects.using(schema_editor.connection.alias).get_or_create(purpose=purpose, defaults={key: getattr(source, key) for key in fields})


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_aicall_step_aicall_task"),

    ]

    operations = [
        migrations.AddField(
            model_name="aimodelprofile",
            name="context_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2048),
                    django.core.validators.MaxValueValidator(131072),
                ],
            ),
        ),
        migrations.AddField(
            model_name="aimodelprofile",
            name="max_output_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(128),
                    django.core.validators.MaxValueValidator(16384),
                ],
            ),
        ),
        migrations.AddField(
            model_name="aimodelprofile",
            name="thinking",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="aimodelprofile",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("review", "政策自动审核与摘要"),
                    ("search", "搜索意图解析"),
                    ("search_summary", "搜索结果归纳"),
                    ("wiki_synthesis", "Wiki 知识页综合"),
                    ("wiki_relations", "政策关系发现"),
                    ("enterprise", "企业与项目资料提取"),
                    ("enterprise_match", "企业政策匹配解读"),
                ],
                max_length=40,
                unique=True,
            ),
        ),
        migrations.RunPython(inherit_models, migrations.RunPython.noop),
    ]
