# Generated by Django 5.2.17 on 2026-09-16 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0001_initial"),
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discovereditem",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="discovereditem",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="discovereditem",
            name="error_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="discovereditem",
            name="lease_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discovereditem",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="discovereditem",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="policies.policy",
            ),
        ),
        migrations.AddField(
            model_name="discovereditem",
            name="retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="discovereditem",
            index=models.Index(fields=["status", "retry_at"], name="ingestion_d_status_90b60a_idx"),
        ),
    ]
