# Generated by Django 5.2.17 on 2026-09-17 02:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ingestion",
            "0002_alter_discovereditem_options_discovereditem_attempts_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcecheckrun",
            name="progress",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="CrawlPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.CharField(default="", max_length=100)),
                ("page", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                ("item_count", models.PositiveIntegerField()),
                ("response_hash", models.CharField(max_length=64)),
                ("object_key", models.CharField(max_length=500)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="ingestion.sourcecheckrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "query", "page"), name="unique_crawl_page"
                    )
                ],
            },
        ),
    ]
