# Generated by Django 5.2.17 on 2026-10-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0007_source_default_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovereditem',
            name='parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
