# Generated by Django 5.2.17 on 2026-09-17 17:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("policies", "0009_requeue_ai_failures_and_opportunities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgePage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=300, unique=True)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("page_type", models.CharField(choices=[("policy", "政策知识页"), ("chain", "政策链"), ("topic", "业务专题"), ("region", "地区专题")], db_index=True, max_length=20)),
                ("title", models.CharField(max_length=500)),
                ("abstract", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("published", "已发布"), ("stale", "需要更新"), ("archived", "已归档")], db_index=True, default="published", max_length=20)),
                ("source_count", models.PositiveIntegerField(default=0)),
                ("built_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["page_type", "title", "id"]},
        ),
        migrations.CreateModel(
            name="KnowledgeBuild",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(default="sync", max_length=20)),
                ("status", models.CharField(choices=[("queued", "等待构建"), ("running", "正在构建"), ("succeeded", "构建完成"), ("failed", "构建失败")], db_index=True, default="queued", max_length=20)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("input_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("result", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="KnowledgeRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                ("body", models.TextField()),
                ("citations", models.JSONField(default=list)),
                ("source_versions", models.JSONField(default=dict)),
                ("input_hash", models.CharField(db_index=True, max_length=64)),
                ("model", models.CharField(blank=True, max_length=200)),
                ("prompt_version", models.CharField(default="wiki-grounded-v1", max_length=40)),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="knowledge.knowledgepage")),
            ],
            options={"ordering": ["-number", "-created_at"]},
        ),
        migrations.AddField(
            model_name="knowledgepage",
            name="current_revision",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="current_for_pages", to="knowledge.knowledgerevision"),
        ),
        migrations.CreateModel(
            name="KnowledgeLintIssue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("severity", models.CharField(default="error", max_length=20)),
                ("message", models.CharField(max_length=500)),
                ("citation_index", models.PositiveIntegerField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lint_issues", to="knowledge.knowledgepage")),
                ("revision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lint_issues", to="knowledge.knowledgerevision")),
            ],
            options={"ordering": ["-created_at", "id"]},
        ),
        migrations.CreateModel(
            name="KnowledgePageSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("policy_version", models.PositiveIntegerField()),
                ("role", models.CharField(default="source", max_length=30)),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="page_sources", to="knowledge.knowledgepage")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="knowledge_sources", to="policies.policy")),
            ],
            options={"constraints": [models.UniqueConstraint(fields=("page", "policy", "role"), name="unique_knowledge_page_source")]},
        ),
        migrations.AddConstraint(
            model_name="knowledgerevision",
            constraint=models.UniqueConstraint(fields=("page", "number"), name="unique_knowledge_page_revision"),
        ),
        migrations.AddIndex(
            model_name="knowledgepage",
            index=models.Index(fields=["status", "page_type"], name="knowledge_k_status_abcda7_idx"),
        ),
    ]
