# Generated by Django 5.2.17 on 2026-09-20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0001_initial"),
        ("policies", "0011_policysource"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeRelationScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("anchor_version", models.PositiveIntegerField()),
                ("candidate_versions", models.JSONField(default=dict)),
                ("input_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "分析完成"), ("failed", "分析失败")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("model", models.CharField(blank=True, max_length=200)),
                (
                    "prompt_version",
                    models.CharField(default="wiki-relations-v1", max_length=40),
                ),
                ("result", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                (
                    "anchor_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_relation_scans",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["anchor_policy", "anchor_version", "status"],
                        name="knowledge_k_anchor__5f4842_idx",
                    )
                ],
            },
        )
    ]
